import React from 'react'
import Link from 'next/link'

import type { GridBlock as GridBlockProps } from '@/payload-types'
import type { Page, Post } from '@/payload-types'

import RichText from '@/components/RichText'
import { Media } from '@/components/Media'
import { cn } from '@/utilities/ui'

// --- Tailwind span class maps (hardcoded so scanner includes all values) ---
const mobileColClass: Record<number, string> = {
  1: 'col-span-1',
  2: 'col-span-2',
  3: 'col-span-3',
  4: 'col-span-4',
}
const desktopColClass: Record<number, string> = {
  1: 'lg:col-span-1',
  2: 'lg:col-span-2',
  3: 'lg:col-span-3',
  4: 'lg:col-span-4',
  5: 'lg:col-span-5',
  6: 'lg:col-span-6',
}
const mobileRowClass: Record<number, string> = {
  1: 'row-span-1',
  2: 'row-span-2',
  3: 'row-span-3',
}
const desktopRowClass: Record<number, string> = {
  1: 'lg:row-span-1',
  2: 'lg:row-span-2',
  3: 'lg:row-span-3',
}
const desktopGridColsClass: Record<number, string> = {
  1: 'lg:grid-cols-1',
  2: 'lg:grid-cols-2',
  3: 'lg:grid-cols-3',
  4: 'lg:grid-cols-4',
  5: 'lg:grid-cols-5',
  6: 'lg:grid-cols-6',
}

// --- Variant theming ---
const containerBg: Record<string, string> = {
  base: 'bg-base-100 border-2 border-base-300',
  primary: 'bg-primary',
}
const textProseClass: Record<string, string> = {
  base: '',
  primary:
    'prose-p:text-primary-content prose-h1:text-primary-content prose-h2:text-primary-content prose-h3:text-primary-content prose-b:text-primary-content prose-b:text-semibold',
}
const linkCellBg: Record<string, string> = {
  base: 'bg-primary prose-p:text-primary-content prose-h1:text-primary-content prose-h2:text-primary-content prose-h3:text-primary-content prose-b:text-primary-content prose-b:text-semibold hover:bg-primary/90',
  primary: 'bg-base-100 text-base-content hover:bg-base-200',
}
const linkCellProseClass: Record<string, string> = {
  base: 'prose-invert',
  primary: '',
}

// --- Typography spacing removal ---
// This targets the inner HTML elements generated by Payload CMS and strips their margins
const noProseMargins =
  'prose-p:!my-0 prose-headings:!my-0 prose-ul:!my-0 prose-ol:!my-0 prose-li:!my-0 prose-blockquote:!my-0 prose-figure:!my-0 prose-hr:!my-0'

// --- Aspect ratio class (mobile uses mobile spans, desktop uses desktop spans) ---
const aspectRatioClass =
  '[aspect-ratio:var(--aspect-mobile)] lg:[aspect-ratio:var(--aspect-desktop)]'

// --- Link href helper (mirrors CMSLink logic) ---
type LinkField = NonNullable<NonNullable<GridBlockProps['cells']>[0]['link']>

function resolveLinkHref(link: LinkField | null | undefined): string {
  if (!link) return '#'
  if (
    link.type === 'reference' &&
    typeof link.reference?.value === 'object' &&
    link.reference.value !== null &&
    'slug' in link.reference.value
  ) {
    const prefix = link.reference.relationTo !== 'pages' ? `/${link.reference.relationTo}` : ''
    return `${prefix}/${(link.reference.value as Page | Post).slug}`
  }
  return link.url ?? '#'
}

// --- Component ---
export const GridBlock: React.FC<GridBlockProps> = ({
  variant = 'primary',
  columns = 4,
  cells,
}) => {
  const v = (variant ?? 'primary') as 'base' | 'primary'
  const cols = Math.max(1, Math.min(6, columns ?? 4))

  return (
    <div className="container">
      <div
        className={cn(
          'grid grid-cols-2 gap-3 sm:gap-8 rounded-2xl p-3 sm:p-8',
          desktopGridColsClass[cols],
          containerBg[v],
        )}
      >
        {(cells ?? []).map((cell, i) => {
          const colSpan = Math.max(1, Math.min(6, cell.colSpan ?? 1))
          const rowSpan = Math.max(1, Math.min(3, cell.rowSpan ?? 1))
          const colSpanMobile = Math.max(1, Math.min(4, cell.colSpanMobile ?? 1))
          const rowSpanMobile = Math.max(1, Math.min(3, cell.rowSpanMobile ?? 1))

          const spanClasses = cn(
            mobileColClass[colSpanMobile],
            desktopColClass[colSpan],
            mobileRowClass[rowSpanMobile],
            desktopRowClass[rowSpan],
          )

          const cellAspectStyle = {
            '--aspect-mobile': `${colSpanMobile} / ${rowSpanMobile}`,
            '--aspect-desktop': `${colSpan} / ${rowSpan}`,
          } as React.CSSProperties

          // ── Text cell ────────────────────────────────────────────────────
          if (cell.cellType === 'text') {
            return (
              <div
                key={i}
                className={cn('flex flex-col rounded-xl p-4 sm:p-6', aspectRatioClass, spanClasses)}
                style={cellAspectStyle}
              >
                {cell.richText && (
                  <RichText
                    className={cn('mb-0 w-full h-full mx-0!', textProseClass[v], noProseMargins)}
                    data={cell.richText}
                    enableGutter={false}
                  />
                )}
              </div>
            )
          }

          // ── Text + Image cell ─────────────────────────────────────────────
          if (cell.cellType === 'textImage') {
            return (
              <div
                key={i}
                className={cn('relative rounded-xl overflow-hidden', aspectRatioClass, spanClasses)}
                style={cellAspectStyle}
              >
                {cell.media && (
                  <Media
                    className="absolute inset-0 w-full h-full"
                    imgClassName="w-full h-full object-cover"
                    resource={cell.media}
                  />
                )}
                {/* dark gradient overlay at bottom for readability */}
                <div className="absolute inset-0 bg-linear-to-t from-black/20 via-black/50 to-black/20" />
                <div className="relative z-10 flex flex-col h-full p-4 sm:p-6">
                  {cell.richText && (
                    <RichText
                      className={cn(
                        'mb-0 mx-0 prose-p:text-primary-content prose-h1:text-primary-content prose-h2:text-primary-content prose-h3:text-primary-content prose-b:text-primary-content prose-b:text-semibold',
                        noProseMargins,
                      )}
                      data={cell.richText}
                      enableGutter={false}
                    />
                  )}
                </div>
              </div>
            )
          }

          // ── Link cell ─────────────────────────────────────────────────────
          if (cell.cellType === 'link') {
            const href = resolveLinkHref(cell.link)
            const newTabProps = cell.link?.newTab
              ? { rel: 'noopener noreferrer' as const, target: '_blank' as const }
              : {}

            return (
              <Link
                key={i}
                href={href}
                {...newTabProps}
                className={cn(
                  'group flex flex-col rounded-xl p-4 sm:p-6 transition-colors',
                  linkCellBg[v],
                  aspectRatioClass,
                  spanClasses,
                )}
                style={cellAspectStyle}
              >
                {/* Arrow in top-right */}
                <div className="flex justify-end">
                  <span className="text-5xl font-bold leading-none transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5">
                    ↗
                  </span>
                </div>

                <div className="flex-1" />

                {cell.richText && (
                  <RichText
                    className={cn('mb-0 w-full mx-0', linkCellProseClass[v], noProseMargins)}
                    data={cell.richText}
                    enableGutter={false}
                  />
                )}
              </Link>
            )
          }

          return null
        })}
      </div>
    </div>
  )
}
