# Multi-stage build producing a slim runtime image from Next's standalone output.
# Requires `output: 'standalone'` in next.config.js.

FROM node:22.17.0-alpine AS base

# ---- dependencies -----------------------------------------------------------
FROM base AS deps
# https://github.com/nodejs/docker-node#nodealpine — sharp and other native deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm ci

# ---- migrator ---------------------------------------------------------------
# Run this against the production database before the app starts. The runtime
# image below is a traced standalone bundle and has no Payload CLI.
FROM base AS migrator
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NODE_ENV=production
CMD ["npx", "payload", "migrate"]

# ---- build ------------------------------------------------------------------
FROM base AS builder
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Payload connects to the database while Next collects page data, so a
# reachable DATABASE_URL is required to build. Any throwaway database will do —
# nothing from it is baked into the image beyond prerendered page content.
ARG DATABASE_URL
# Build-time only. The real secret is supplied to the container at runtime.
ARG PAYLOAD_SECRET=build-time-placeholder
ARG NEXT_PUBLIC_SERVER_URL

ENV DATABASE_URL=$DATABASE_URL \
    PAYLOAD_SECRET=$PAYLOAD_SECRET \
    NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL \
    NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production

# Page data is collected from the database during the build, so the schema has
# to exist before Next runs.
RUN npx payload migrate && npm run build

# ---- runtime ----------------------------------------------------------------
FROM base AS runner
RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Payload writes uploads here (see Media.upload.staticDir). Mount a volume on
# this path or uploads are lost when the container is replaced.
RUN mkdir -p /app/public/media && chown -R nextjs:nodejs /app/public/media

USER nextjs
EXPOSE 3000

# server.js is generated by next build's standalone output
CMD ["node", "server.js"]
